### PR TITLE
Regenerate with GoGo Protobuf v1.1.1

### LINKED ISSUE #2: Generated types are no longer convertable to golang/protobuf types
Since https://github.com/google/go-genproto/pull/65 was merged, `google.golang.org/genproto` types have the new `protoc-gen-go` fields:

https://github.com/jadekler/go-genproto/blob/c60d0593e41763b34a56c7ae500acf1d232486e4/googleapis/rpc/status/status.pb.go#L74

```go
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	// user-facing error message should be localized and sent in the
	// [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// A list of messages that carry the error details.  There is a common set of
	// message types for APIs to use.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}
```

This means the generated types in this repo are no longer convertable, i.e. this is no longer possible:

```go
var _ *rpc.Status = (*rpc.Status)(&status.Status{})
```

Will gogoproto be updated (is it already?) to include these fields as well? If so we need to regenerate these types again.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes #2 

Also adds dep files for reproducible builds and removes unused tests.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Hmmm, I wonder why the hashes are not deterministic.
Do you think it might just be a different version of protoc?

I have seen `tip` causing problems for `golang/protobuf`, maybe we should rather update go with manual steps.  What do you think?

**Comment by awalterschulze** [comment]
The cleanup and updates are much appreciated.  This looks great :)

**Comment by johanbrandhorst** [comment]
Just a `protoc` version mismatch.

**Review by awalterschulze — APPROVED** [review]

**Comment by awalterschulze** [comment]
Thank you so much :)

**Pull request merged**
