### PR TITLE
Add longrunning

### PR DESCRIPTION
**Pull request by sgtsquiggs**
Currently fails during `make regenerate`:

```
protoc \
        --gogogoogleapis_out=\
        Mgoogle/api/annotations.proto=github.com/gogo/protobuf/api,\
        Mgoogle/api/http.proto=github.com/gogo/protobuf/api,\
        Mgoogle/rpc/status.proto=github.com/gogo/protobuf/rpc,\
        Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
        Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,\
        Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
        Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor,\
        :. \
        -I=. \
        google/longrunning/operations.proto
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1266fc1]

goroutine 1 [running]:
github.com/gogo/protobuf/plugin/compare.(*plugin).generateMessage(0xc000096120, 0xc0001bb720, 0xc0001bb7c0)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/plugin/compare/compare.go:437 +0xac1
github.com/gogo/protobuf/plugin/compare.(*plugin).Generate(0xc000096120, 0xc0001bb720)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/plugin/compare/compare.go:72 +0x292
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).runPlugins(0xc0000d4f00, 0xc0001bb720)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/protoc-gen-gogo/generator/generator.go:1183 +0x6d
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).generate(0xc0000d4f00, 0xc0001bb720)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/protoc-gen-gogo/generator/generator.go:1232 +0x6d4
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).GenerateAllFiles(0xc0000d4f00)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/protoc-gen-gogo/generator/generator.go:1160 +0x27e
github.com/gogo/protobuf/vanity/command.Generate(0xc000096180, 0x13d6c30)
        /Users/mcrenshaw/Code/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/vanity/command/command.go:131 +0x17c
main.main()
        /Users/mcrenshaw/Code/googleapis/protoc-gen-gogogoogleapis/main.go:69 +0x56a
--gogogoogleapis_out: protoc-gen-gogogoogleapis: Plugin failed with status code 2.
make: *** [regenerate] Error 1
```

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
:thinking: any idea why?

**Comment by sgtsquiggs** [comment]
Not sure yet. Looks like it fails writing out code for the oneof field

**Comment by sgtsquiggs** [comment]
😎

**Comment by sgtsquiggs** [comment]
google/longrunning/operations.pb.go imports `google/api`; I need to fix that.

**Comment by johanbrandhorst** [comment]
Nice, thanks for your contribution!

**Pull request merged**
