### PR TITLE
Regenrate files to fix the protobuf issue.

### PR DESCRIPTION
**Pull request by abhijitherekar**
We need to regenrate the files due the following PR
in protobuf: https://github.com/gogo/protobuf/pull/560

### CODE REVIEW

**Comment by abhijitherekar** [comment]
@awalterschulze @johanbrandhorst  
Please, review the PR.

**Comment by abhijitherekar** [comment]
Looked at the travis failure, that looks strange, the command `git diff --exit-code` is failing. I don't have any unstaged files. 
Please, let me know if there anything that I am missing.

**Comment by abhijitherekar** [comment]
I have upgraded the protobuf to point it 1.3.0 and regenerated the protobuf files. The travis has passed with those changes. 

Please, review.

Thanks

**Comment by johanbrandhorst** [comment]
I'll make an upstream sync and make another release.

**Pull request merged**
